### ISSUE TITLE
如何添加bilibili的ijkplayer的IjkplayerMediaPlayer作为默认播放器

### ISSUE THREAD

**Issue by ghost** [jcodeing/KMedia#1]
如何添加bilibili的ijkplayer的IjkplayerMediaPlayer作为你的默认播放器，目前里面放置的是google的exoplayer。

**Comment by akerush** [comment]
README中有写, 实现IMediaPlayer接口, 参考KMedia-Mpe:ExoMediaPlayer

**Comment by jcodeing** [comment]
README中有写, 实现IMediaPlayer接口, 参考KMedia-Mpe:ExoMediaPlayer
