### ISSUE TITLE
请问这个怎么播放音频呀

### ISSUE THREAD

**Issue by KnowledgeBeggar** [jcodeing/KMedia#2]

**Comment by jcodeing** [comment]
先依赖
compile 'com.jcodeing:kmedia-core:r1.0.10'
compile 'com.jcodeing:kmedia-exo:r1.0.10'
再播放
Player player = new Player(context).init(new ExoMediaPlayer(context));
player.play(uri); //另外变速可直接调用player.setPlaybackSpeed(speed);
详见Doc
https://jcodeing.github.io/KMedia-Core/
README中基本都有介绍

**Comment by KnowledgeBeggar** [comment]
不是说api最少支持7以上吗，怎么我依赖exo那个库时会报最低版本过低呢

**Comment by jcodeing** [comment]
你有么有认认真真的去看README! 那是支持VectorDrawable好嘛!!
另外KMedia-Core:minSdkVersion 9, Exo:minSdkVersion 16.
