### ISSUE TITLE
KMedia-core的实现原理是什么样子的？*player这些之间的关系，看着有点乱，麻烦解释一下，谢谢

### ISSUE THREAD

**Issue by ghost** [jcodeing/KMedia#3]

**Comment by jcodeing** [comment]
实现原理: 就是你造一辆机车(摩托车), 然后骑着它在五环路上驰骋....
基本关系: ...
IPlayerBase //接口//定义Player通用方法//~机车基本架构
|--IMediaPlayer //接口//实现类-负责媒体基础播放//~机车的发动机(引擎)
|----AMediaPlayer //抽象类//实现公共方法//~拧个螺丝,组一套离合片这些小活我来
|------AndroidMediaPlayer //类//Android原生媒体引擎封装//~造一个国产的引擎
|------ExoMediaPlayer //类//Exo媒体引擎封装//~来一个进口的引擎
|------OtherMediaPlayer//类//可添加第三方媒体引擎(当然亦可直接实现IMediaPlayer)
|--IPlayer //接口//实现类-负责封装扩展媒体引擎//~可理解为一辆拽来就能驰骋的机车
|----APlayer //抽象类//~可理解为实现机车的基本功能
|------Player //类//简单的实现类//~可理解为给机车喷个漆加个音响等
|------OtherPlayer //类//~可自行DIY这辆机车,达到你心目中的高配
|----APlayerBinding //抽象类//~给你加个天空套,可以在云中自由翱翔
|------PlayerBinding //类//简单的实现类//~....
|------OtherPlayerBinding //类//自行DIY....
...
造一辆机车. 可以选择自己中意的引擎....
Player player = new Player(context).init(new AndroidMediaPlayer());
player...... 骑着它在五环路上驰骋....
