### ISSUE TITLE
开issue来点赞

### ISSUE THREAD

**Issue by feer921** [jcodeing/KMedia#4]
![qq 20180312155820](https://user-images.githubusercontent.com/6622321/37271528-3a2b419a-260e-11e8-8f08-48b8e11de0b7.png)

非常好的一个开源媒体播放框架，多推广推广啊，从github搜索以及外部来看，被标识为了shell类项目

**Comment by jcodeing** [comment]
github识别项目类型算法还是那么有个性. 
上项目后以为过段时间github会升级算法或支持手动添加项目类型.
然而现在还是要通过.gitattributes 强行掰正了!
一个人推广毕竟还是有限, 目前基本能分享的地方都已经推广过.
最重要的还是, 靠大家的力量了. 希望这个开源框架可以帮到大家. 谢谢@feer921
